### ISSUE TITLE
Docs for contributing guidelines

### ISSUE THREAD

**Issue by HargovindArora** [openwisp/openwisp2-docs#7]
A well-structured guide has to be prepared so that first-time contributors can know the do's and how's of contributing to this very organization.

**Comment by xamfy** [comment]
@HargovindArora are you working on this?

**Comment by HargovindArora** [comment]
@xamfy. Please go ahead. Currently I'm busy with the glossary thing

**Comment by HargovindArora** [comment]
#25

**Comment by nemesisdesign** [comment]
Moving here the notes I left on the original PR:

1. we should make it clear that you don't have to be a programmer in order to contribute, because non programmers can help us a lot with documentation, promotion, tutorials, improving designs, making videos
2. we should encourage anyone that is using openwisp to talk about their experience, either on social media (twitter, facebook), by writing a blog post, by publishing a video on youtube or talking at a conference, we should make it clear that this type of contribution is very helpful for the project because it not only sends us feedback but will also help us to promote the project to new potential users and contribtuors
3. we need a style convention section in which we outline the commit message style we use and a few things about python, javascript and openwrt stuff, you can leave these blank and I will fill it in the following days

**Comment by HargovindArora** [comment]
Yeah, this is fine here! :+1:
