### ISSUE TITLE
Repository changes not being reflected to website

### ISSUE THREAD

**Issue by TheOneAboveAllTitan** [openwisp/openwisp2-docs#90]
Changes addressed in #87 and #83 are not reflected on the website.

**Comment by atb00ker** [comment]
Actually, the website is not hosted on GitHub but on a seperate server. It'll take a while because it needs to manually updated.
So, It might be updated with a release but for small changes it's not usually feasible update again and again but It will update it at some point, don't worry!

Closing this issue because it's not really a bug! :smile:
