### ISSUE TITLE
[docs] Make clear to have 1 PR for 1 feature

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp2-docs#98]
Contributors should try to send 1 PR for 1 feature.
If they are working on a PR that touches a group of related features, they can work on it in 1 PR if they prefer, but have to have 1 commit for each feature they change/introduce/remove.

Maintainers can work on branches and open PRs to merge various changes in one branch.

**Comment by Kajol-Kumari** [comment]
@nemesisdesign I have few questions regarding this issue, It would be great if you could clarify:

1. Do we want it like 1 commit per PR (i.e contributors need to squash the commits after the PR gets approved)
2. If a PR covers multiple features, it should have 1 commit per feature and after review it should be squashed in a single one after being approved by the maintainers.
3. These instructions will go under `readme.md` or should I create a new file named `contribution-guidelines.md` ?

**Comment by pandafy** [comment]
Hi @Kajol-Kumari ,

> * Do we want it like 1 commit per PR (i.e contributors need to squash the commits after the PR gets approved)
> * If a PR covers multiple features, it should have 1 commit per feature and after review it should be squashed in a single one after being approved by the maintainers.

We usually encourage contributors to send one commit per PR per feature . But sometimes, it is not feasible if two features are interlinked.

Let's take a scenario from [openwisp-notifications](https://github.com/openwisp/openwisp-notifications) for reference. 
The features getting added in https://github.com/openwisp/openwisp-notifications/pull/52 and https://github.com/openwisp/openwisp-notifications/pull/57 were closely related. If any changes were requested on any of the PRs, the other PR had to be updated. This made working on these feature a bit tedious. At https://github.com/openwisp/openwisp-notifications/pull/52#issuecomment-654425826 it was decided to continue their development in only one PR and maintain different commits for each feature.You can see that there are multiple commits added in [openwisp/openwisp-notifications#57](https://github.com/openwisp/openwisp-notifications/pull/57/commits). 

With this issues, we are encouraging contributors to follow that paradigm(like in [openwisp/openwisp-notifications#57](https://github.com/openwisp/openwisp-notifications/pull/57/commits)) since it maintains cleaner commit history and we can easily traceback changes in future. 

Squashing those commits will defy the sole purpose of bringing this change. So. we are **not** aiming for squashed commits in this scenario

> * These instructions will go under `readme.md` or should I create a new file named `contribution-guidelines.md` ?

These instructions will go in https://github.com/openwisp/openwisp2-docs/blob/master/developer/contributing.rst


I hope this helps you :smile:

**Comment by nemesisdesign** [comment]
Thanks @pandafy for the in-depth explanation!

@Kajol-Kumari what @pandafy wrote is correct.

Here's straight answers to your questions.

> @nemesisdesign I have few questions regarding this issue, It would be great if you could clarify:
> 
> 1. Do we want it like 1 commit per PR (i.e contributors need to squash the commits after the PR gets approved)

Possibly 1 commit per feature, and possibly one feature/change/fix per PR.
Occasionally it's ok to work on related features in the same PR with a few commits.
Maintainers can work on branches and merge multiple commits if needed, as long as specific features are always added as one commit.
**We strive to make sure the result of every commit is a functioning version of the module.** This is a concept we didn't make explicit before and would be good to add it. 

> 2. If a PR covers multiple features, it should have 1 commit per feature and after review it should be squashed in a single one after being approved by the maintainers.

Will not be squashed.

> 3. These instructions will go under `readme.md` or should I create a new file named `contribution-guidelines.md` ?

Must go here: https://github.com/openwisp/openwisp2-docs/blob/master/developer/contributing.rst
They're published at https://openwisp.io/docs/developer/contributing.html

Thanks!
